# Site settings
title: Piyush Gupta
description: My Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Helloo, I am Piyush Gupta
user_description: I am a student aspiring to be a Engineer. I love coding, learning new technologies related to computer science, playing video games and swimming.
email: piyushji16@gmail.com
linkedin_username: https://www.linkedin.com/in/rishabhgupta34/
github_username:  https://github.com/guptapiyush16
# Google-analytics
google-analytics:
  id: UA-136470922-1

exclude: ['package.json', 'src' , 'node_modules']
